import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import ts from 'typescript';
async function load(path,dependencies={}){let code=ts.transpileModule(await readFile(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;for(const [name,url]of Object.entries(dependencies))code=code.replace(`from "${name}"`,`from ${JSON.stringify(url)}`);const url='data:text/javascript;base64,'+Buffer.from(code).toString('base64');return{url,...await import(url)};}
const location=await load('lib/store-location.ts'),store=await load('lib/customer-store.ts',{'./store-location':location.url});
const pin={address:'ร้าน',latitude:'13.7563',longitude:'100.5018'};
assert.deepEqual(location.storeCoordinates(pin),[13.7563,100.5018]);
for(const invalid of [{...pin,latitude:''},{...pin,latitude:'Infinity'},{...pin,latitude:'86'},{...pin,longitude:'181'}])assert.equal(location.storeCoordinates(invalid),null);
assert.equal(location.storeDirections(location.emptyStoreLocation),null);
assert.equal(new URL(location.storeDirections(pin)).searchParams.get('destination'),'13.7563,100.5018');
assert.equal(new URL(location.googleMapEmbed(pin)).hostname,'www.google.com');
assert.equal(new URL(location.googleMapEmbed(pin)).searchParams.get('q'),'13.7563,100.5018');
assert.deepEqual(location.parseGoogleCoordinates('13.7563, 100.5018'),[13.7563,100.5018]);
assert.deepEqual(location.parseGoogleCoordinates('https://www.google.com/maps/place/shop/@13.7,100.5,16z/data=!3d7.1!4d100.2'),[7.1,100.2],'Use the selected place rather than camera center');
assert.equal(location.parseGoogleCoordinates('https://fake.example/maps/@13.7,100.5'),null);
const daily=['จันทร์','อังคาร','พุธ','พฤหัสบดี','ศุกร์','เสาร์','อาทิตย์'].map(day=>({day,open:true,opensAt:'08:00',closesAt:'20:30'}));
assert.deepEqual(store.compactStoreHours(daily),[{days:'เปิดทุกวัน',time:'08:00 – 20:30 น.',closed:false}]);
const different=daily.map(day=>day.day==='อาทิตย์'?{...day,open:false}:day);
assert.deepEqual(store.compactStoreHours(different),[{days:'เปิดจันทร์–เสาร์',time:'08:00 – 20:30 น.',closed:false},{days:'หยุดอาทิตย์',time:'หยุด',closed:true}]);
const info=store.customerStoreInfo({description:'ข้อมูลร้าน',store_hours_enabled:true,weekly_hours:[{day:'จันทร์',open:true,opensAt:'08:00',closesAt:'20:30'},{day:'อังคาร',open:false,opensAt:'08:00',closesAt:'20:30'}],contacts:[{id:1,active:true},{id:2,active:false}],card_design:{store_location:pin}});
assert.deepEqual(info.location,pin);assert.equal(info.contacts.length,1);
assert.equal(store.storeStatus(info,new Date('2026-10-12T08:00:00+07:00')),'open');
assert.equal(store.storeStatus(info,new Date('2026-10-12T20:30:00+07:00')),'closed');
assert.equal(store.storeStatus({...info,hoursEnabled:false},new Date()),null);
const overnight={...info,hours:[{day:'จันทร์',open:true,opensAt:'22:00',closesAt:'02:00'}]};
assert.equal(store.storeStatus(overnight,new Date('2026-10-13T01:30:00+07:00')),'open');
assert.equal(store.storeStatus(overnight,new Date('2026-10-13T02:00:00+07:00')),'closed');
assert.equal(store.storeStatus({...info,closure:{enabled:true,startsOn:'2026-10-12',endsOn:'2026-10-13'}},new Date('2026-10-12T10:00:00+07:00')),'holiday');
assert.equal(store.contactHref({platform:'website',url:'javascript:alert(1)'}),null);
assert.equal(store.contactHref({platform:'phone',value:'099-123-4567'}),'tel:0991234567');
console.log('PASS: public shop location roundtrip, map coordinate validation, directions, active contacts, safe links, Bangkok opening/closing boundaries, overnight hours and temporary closures.');
