import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import ts from 'typescript';
const {PGlite}=await import('../.tmp/transaction-verification/node_modules/@electric-sql/pglite/dist/index.js');
const db=new PGlite();
const fixture=await readFile(new URL('./transaction-reversals.mjs',import.meta.url),'utf8');
await db.exec(fixture.match(/await db.exec\(`([\s\S]*?)`\);/)[1]);
await db.exec("alter role postgres bypassrls;alter table members add status text default 'active';create table point_expiry_runs(owner_id uuid,closing_year int,members_affected int,points_expired int,primary key(owner_id,closing_year));");
for(const name of ['20261003083711_transaction_reversals.sql','20261003083741_transaction_reversal_details.sql','20261003141506_game_platform.sql','20261004003000_game_actor_verification_permissions.sql','20261004172130_flexible_points_history_cleanup.sql'])await db.exec(await readFile(new URL('../supabase/migrations/'+name,import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../supabase/migrations/20261004181534_preserve_reports_after_history_cleanup.sql',import.meta.url),'utf8'));
const owner=randomUUID(),other=randomUUID(),member=randomUUID(),otherMember=randomUUID(),today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),year=Number(today.slice(0,4));
await db.query('insert into auth.users values($1,now()),($2,now())',[owner,other]);
await db.query('insert into store_settings values($1,$2),($3,$4)',[owner,{points_expiration:'รีทุกสิ้นปี',points_expiration_month:today.slice(5,7),points_expiration_day:today.slice(8,10)},other,{}]);
await db.query("insert into members(id,owner_id,points,spending,level)values($1,$2,100,900,'Member'),($3,$4,80,0,'Member')",[member,owner,otherMember,other]);
await db.query('insert into game_programs values($1,500,true)',[owner]);
const insert=async(points,sale=0,rank=null,birthday=null,who=member,shop=owner)=>{
 const id=randomUUID();await db.query("insert into points_transactions(id,owner_id,member_id,points_delta,sale_amount,transaction_type,created_at,rank_bonus_level,birthday_bonus_year)values($1,$2,$3,$4,$5,'earn',now()-interval '1 minute',$6,$7)",[id,shop,who,points,sale,rank,birthday]);return id;
};
await insert(20,700);await insert(-3);await insert(5,0,'Gold');await insert(7,0,null,year);await insert(9,0,null,null,otherMember,other);
const snapshot=new Date().toISOString(),from=`${year}-01-01T00:00:00+07:00`,to=new Date(Date.parse(`${today}T00:00:00+07:00`)+86400000).toISOString();
const wallet=async()=>(await db.query('select balance,carry,spent from game_wallets where member_id=$1',[member])).rows[0];
const before=await wallet();
const reportRows=async()=>(await db.query('select * from crm_report_summary_rows($1)',[owner])).rows;
const reportBefore=await reportRows();
const clear=async(expected=2,actor=owner)=>db.query('select clear_points_history_range($1,$2,$3,$4,$5,$6) result',[owner,actor,from,to,snapshot,expected]);
await assert.rejects(clear(2,other),/FORBIDDEN/);await assert.rejects(clear(3),/HISTORY_CHANGED/);
assert.equal((await db.query('select count(*)::int n from points_transactions')).rows[0].n,5);
const result=(await clear()).rows[0].result;assert.deepEqual(result,{deleted:2,remaining:0});
assert.deepEqual(await reportRows(),reportBefore,'Report totals/daily/customer rankings survive cleanup');
assert.equal((await db.query('select sale_amount from private.report_history_daily where member_id=$1',[member])).rows[0].sale_amount,'700');
assert.deepEqual(await wallet(),before,'Cleanup must not reverse earned game tickets');
assert.equal((await db.query('select points from members where id=$1',[member])).rows[0].points,100);
assert.equal((await db.query('select positive_points from private.points_history_rollups')).rows[0].positive_points,20);
assert.equal((await db.query('select count(*)::int n from points_transactions where owner_id=$1',[other])).rows[0].n,1,'Other shop untouched');
assert.equal((await db.query('select count(*)::int n from points_transactions where member_id=$1',[member])).rows[0].n,2,'Birthday/rank anti-duplicate markers retained');
assert.equal((await db.query("select count(*)::int n from audit_logs where action='clear_points_history'")).rows[0].n,1);
await assert.rejects(clear(),/HISTORY_CHANGED/);
const late=await insert(10,100); // Written after snapshot; cannot be wiped by the old preview.
assert.equal((await db.query("select current_setting('tammy.history_cleanup',true) as flag")).rows[0].flag,'','Cleanup flag restored');
await db.query('select private.expire_year_end_points()');
assert.equal((await db.query('select points from members where id=$1',[member])).rows[0].points,42,'Annual reset includes archived positive earnings and retained markers');
await db.query('delete from points_transactions where id=$1',[late]);
assert.equal(Number((await wallet()).carry),200,'Ordinary deletion still reverses its game purchase');
assert.equal((await wallet()).balance,1,'Archived purchase credits remain available in a later replay');
await db.exec('set role authenticated');await assert.rejects(clear(),/permission denied/);await assert.rejects(db.query('select * from private.points_history_rollups'),/permission denied/);await db.exec('reset role');

async function load(path){const source=await readFile(new URL('../'+path,import.meta.url),'utf8'),code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext}}).outputText;return import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));}
const {historyRange}=await load('lib/points-history-range.ts');
const range=historyRange({from:`${year}-01-01`,to:today});assert.equal(range.fromInstant,`${year-1}-12-31T17:00:00.000Z`);assert.equal(range.toInstant,to);
assert.equal(historyRange({from:'2026-02-30',to:today}),null);assert.equal(historyRange({from:today,to:'2099-12-31'}),null);assert.equal(historyRange({from:today,to:`${year}-01-01`}),null);
const {memberPetCounts}=await load('lib/member-pet-counts.ts');
assert.deepEqual(memberPetCounts({dog_count:3,cat_count:2},[]),{dogs:3,cats:2});assert.deepEqual(memberPetCounts({dog_count:0,cat_count:0},[{species:'dog'}]),{dogs:0,cats:0});assert.deepEqual(memberPetCounts({},[{species:'dog'},{species:'cat'}]),{dogs:1,cats:1});
await db.exec("alter table members add member_code text,add name text,add line_display_name text;alter table coupons add title text;alter table rewards add title text;alter table member_coupon_claims add unique(owner_id,coupon_id,member_id);");
await db.exec(await readFile(new URL('../supabase/migrations/20261003172834_game_history_cleanup.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../supabase/migrations/20261004174245_unified_transaction_history_cleanup.sql',import.meta.url),'utf8'));
const coupon=randomUUID(),reward=randomUUID();
await db.query("insert into coupons(id,owner_id,title,used_count) values($1,$2,'คูปอง',1)",[coupon,owner]);
await db.query("insert into rewards(id,owner_id,title,stock) values($1,$2,'รางวัล',3)",[reward,owner]);
await db.query("update members set member_code='TEST',name='สมาชิก',line_display_name='LINE' where id=$1",[member]);
await insert(4);
await db.query("insert into redemptions(owner_id,member_id,coupon_id,points_spent,status,redeemed_at) values($1,$2,$3,0,'completed',now()-interval '20 seconds')",[owner,member,coupon]);
await db.query("insert into redemptions(owner_id,member_id,reward_id,points_spent,status,redeemed_at) values($1,$2,$3,8,'completed',now()-interval '10 seconds')",[owner,member,reward]);
const cutoff=new Date().toISOString();
const timeline=(await db.query('select * from transaction_history_rows($1,$2,$3,$4)',[owner,from,to,cutoff])).rows;
assert.equal(timeline.length,6);assert.ok(timeline.every((r,i)=>!i||new Date(r.created_at)>=new Date(timeline[i-1].created_at)));
assert.ok(timeline.every(r=>r.member_code==='TEST'&&r.line_name==='LINE'));
const currentWallet=await wallet();
const summaryBefore=await reportRows();
const combined=(await db.query('select clear_transaction_history_range($1,$2,$3,$4,$5,4) result',[owner,owner,from,to,cutoff])).rows[0].result;
assert.deepEqual(combined,{deleted:4,remaining:0});assert.deepEqual(await wallet(),currentWallet);
assert.deepEqual(await reportRows(),summaryBefore,'Combined cleanup preserves report summary without double counting');
assert.equal((await db.query('select status from member_coupon_claims where coupon_id=$1',[coupon])).rows[0].status,'used');
assert.equal((await db.query('select stock from rewards where id=$1',[reward])).rows[0].stock,3);
assert.equal((await db.query('select count(*)::int n from redemptions where owner_id=$1',[owner])).rows[0].n,0);
await db.exec('set role authenticated');await assert.rejects(db.query('select * from transaction_history_rows($1,$2,$3,$4)',[owner,from,to,cutoff]),/permission denied/);await db.exec('reset role');
await db.exec(await readFile(new URL('../supabase/migrations/20261004182401_include_audit_logs_in_history_cleanup.sql',import.meta.url),'utf8'));
await db.query("insert into audit_logs(owner_id,actor_id,action,created_at) values($1,$1,'test-old',now()-interval '1 minute'),($2,$2,'other-shop',now()-interval '1 minute'),($1,$1,'future',now()+interval '1 minute')",[owner,other]);
const auditSnapshot=new Date().toISOString();
const auditCount=(await db.query('select count(*)::int n from audit_logs where owner_id=$1 and created_at >= $2 and created_at<$3 and created_at<=$4',[owner,from,to,auditSnapshot])).rows[0].n;
const archivedReport=await reportRows();
const auditExport=(await db.query('select * from transaction_history_rows($1,$2,$3,$4)',[owner,from,to,auditSnapshot])).rows;
assert.equal(auditExport.filter(r=>r.entry_type==='audit').length,auditCount);
await assert.rejects(db.query('select clear_transaction_history_range($1,$2,$3,$4,$5,$6)',[owner,other,from,to,auditSnapshot,auditCount]),/FORBIDDEN/);
await assert.rejects(db.query('select clear_transaction_history_range($1,$2,$3,$4,$5,$6)',[owner,owner,from,to,auditSnapshot,auditCount+1]),/HISTORY_CHANGED/);
const auditClear=(await db.query('select clear_transaction_history_range($1,$2,$3,$4,$5,$6) result',[owner,owner,from,to,auditSnapshot,auditCount])).rows[0].result;
assert.deepEqual(auditClear,{deleted:auditCount,remaining:0});assert.deepEqual(await reportRows(),archivedReport);
assert.equal((await db.query("select count(*)::int n from audit_logs where action='test-old'")).rows[0].n,0);
assert.equal((await db.query("select count(*)::int n from audit_logs where action in ('other-shop','future')")).rows[0].n,2);
await db.exec('set role authenticated');await assert.rejects(db.query('select clear_transaction_history_range($1,$2,$3,$4,$5,$6)',[owner,owner,from,to,auditSnapshot,1]),/permission denied/);await db.exec('reset role');
await db.exec(`create function public.award_points(uuid,numeric,integer,text) returns boolean language plpgsql as $$declare m public.members;today_bkk date:=(now() at time zone 'Asia/Bangkok')::date;claimed boolean;begin select * into m from public.members where id=$1;select exists(select 1 from public.points_transactions where member_id=m.id and birthday_bonus_year=extract(year from today_bkk)::integer) into claimed;return claimed;end$$;`);
await db.exec(await readFile(new URL('../supabase/migrations/20261004184441_clear_bonus_history_keep_receipts.sql',import.meta.url),'utf8'));
const bonusSnapshot=new Date().toISOString();
const bonusAudit=(await db.query('select count(*)::int n from audit_logs where owner_id=$1 and created_at >=$2 and created_at<$3 and created_at<=$4',[owner,from,to,bonusSnapshot])).rows[0].n;
const bonusWallet=await wallet(),bonusReport=await reportRows(),bonusBalance=(await db.query('select points from members where id=$1',[member])).rows[0].points;
const bonusResult=(await db.query('select clear_transaction_history_range($1,$2,$3,$4,$5,$6) result',[owner,owner,from,to,bonusSnapshot,bonusAudit+2])).rows[0].result;
assert.deepEqual(bonusResult,{deleted:bonusAudit+2,remaining:0});
assert.equal((await db.query('select count(*)::int n from points_transactions where owner_id=$1',[owner])).rows[0].n,0);
assert.equal((await db.query('select count(*)::int n from private.member_bonus_receipts where owner_id=$1',[owner])).rows[0].n,2);
assert.deepEqual(await wallet(),bonusWallet);assert.deepEqual(await reportRows(),bonusReport);
assert.equal((await db.query('select points from members where id=$1',[member])).rows[0].points,bonusBalance);
assert.equal((await db.query('select award_points($1,1,1,$2) claimed',[member,'test'])).rows[0].claimed,true,'Birthday receipt prevents re-awarding after cleanup');
await insert(5,0,'Gold');await insert(7,0,null,year);
assert.equal((await db.query('select count(*)::int n from points_transactions where owner_id=$1',[owner])).rows[0].n,0,'Archived bonuses cannot be inserted again');
await db.exec(await readFile(new URL('../supabase/migrations/20261010204726_remove_lucky_games.sql',import.meta.url),'utf8'));
assert.equal((await db.query("select count(*)::int n from pg_tables where schemaname in ('public','private') and (tablename like 'game_%' or tablename='crm_games')")).rows[0].n,0);
await insert(4,120);
const afterRemovalSnapshot=new Date().toISOString(),remainingRows=(await db.query('select * from transaction_history_rows($1,$2,$3,$4)',[owner,from,to,afterRemovalSnapshot])).rows;
assert.ok(remainingRows.some(r=>r.entry_type==='earn'),'Ordinary history export survives game removal');
const reportAfterRemoval=await reportRows();
const resultAfterRemoval=(await db.query('select clear_transaction_history_range($1,$2,$3,$4,$5,$6) result',[owner,owner,from,to,afterRemovalSnapshot,remainingRows.length])).rows[0].result;
assert.equal(resultAfterRemoval.remaining,0);assert.deepEqual(await reportRows(),reportAfterRemoval);
await db.close();console.log('PASS: all history including bonuses/audit cleared; compact receipts prevent repeat bonuses; reports, balances, rights, owner/date/snapshot scope preserved.');
