"use client";
import Image from "next/image";
import { Bell, CreditCard, Gift, Home, LogIn, Newspaper, TicketPercent, UserRound } from "lucide-react";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase/client";
import type { ShopDay, StoreContact, TemporaryClosure } from "@/lib/settings";
import { normalizeCardDesign, type CardDesign } from "@/lib/card-design";
import { MemberCard } from "./member-card";
import { CustomerPopupCarousel } from "./customer-popup-carousel";
import { normalizePopupDisplay, type PopupDisplay } from "@/lib/popup-content";
import Link from "next/link";

type Tab="home"|"card"|"news"|"coupons"|"account";
type PublicShop = { shop_name:string; shop_name_en:string; description:string; welcome_message:string; logo_url:string|null; contacts:StoreContact[]; store_hours_enabled:boolean; weekly_hours:ShopDay[]; temporary_closure:TemporaryClosure; card_design:CardDesign };

const coupons=[{code:"WELCOME10",title:"สมาชิกใหม่ลด 10%",detail:"ขั้นต่ำ 500 บาท",color:"coral"},{code:"PET100",title:"ลดทันที 100 บาท",detail:"ขั้นต่ำ 1,000 บาท",color:"gold"},{code:"GROOM15",title:"กรูมมิ่งลด 15%",detail:"ใช้กับบริการอาบน้ำและตัดขน",color:"mint"}];
function safeContactUrl(value:string){try{const url=new URL(value);return ["https:","http:","tel:"].includes(url.protocol)?value:undefined}catch{return undefined}}
export function CustomerPortal(){const[tab,setTab]=useState<Tab>("home");const[loggedIn,setLoggedIn]=useState(false);const[message,setMessage]=useState("");const[shop,setShop]=useState<PublicShop|null>(null);const[popupItems,setPopupItems]=useState<PopupDisplay[]>([]);const[popupEnabled,setPopupEnabled]=useState(false);const[popupOpen,setPopupOpen]=useState(false);
useEffect(()=>{if(!supabase)return;void supabase.from("public_shop_profiles").select("shop_name,shop_name_en,description,welcome_message,logo_url,contacts,store_hours_enabled,weekly_hours,temporary_closure,card_design").eq("slug","tammy").maybeSingle().then(({data})=>{if(data){const config=data.card_design as Record<string,unknown>|null;setShop({...data,card_design:normalizeCardDesign(data.card_design)} as PublicShop);setPopupItems(normalizePopupDisplay(config?.popup_content).filter(item=>item.active));setPopupEnabled(config?.popup_enabled===true)}})},[]);
const todayParts=new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Bangkok",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());
const datePart=(type:string)=>todayParts.find(part=>part.type===type)?.value||"";
const today=`${datePart("year")}-${datePart("month")}-${datePart("day")}`;
const closure=shop?.temporary_closure;
const closedNow=Boolean(closure?.enabled&&closure.startsOn&&closure.endsOn&&today>=closure.startsOn&&today<=closure.endsOn);
function login(form:FormData){if(!form.get("phone")||!form.get("pin"))return;setLoggedIn(true);setTab("card");setMessage("กำลังแสดงบัตรตัวอย่าง · ยังไม่เชื่อมบัญชีสมาชิกจริง");if(popupEnabled&&popupItems.length)setPopupOpen(true);}
return <main className="customer-portal"><header className="customer-top"><div><Image src={shop?.logo_url||"/assets/tammy-logo-cat.png"} alt={shop?.shop_name||"Tammy"} width={54} height={54} unoptimized={Boolean(shop?.logo_url)}/><span><strong>{shop?.shop_name||"TAMMY"}</strong><small>{shop?.shop_name_en||"PET SHOP"}</small></span></div><button aria-label="การแจ้งเตือน"><Bell/></button></header>
<section className="customer-content">{message&&<p className="customer-toast">{message}</p>}{tab==="home"&&<><div className="customer-hero"><span>สวัสดีค่ะ 👋</span><h1>{loggedIn?"คุณสมาชิก":`ยินดีต้อนรับสู่ ${shop?.shop_name||"Tammy"}`}</h1><p>{shop?.welcome_message||"สะสมแต้มง่าย แลกของรางวัลและคูปองได้ทุกวัน"}</p><Image src="/assets/member-mascot-cat.png" alt="" width={150} height={180}/></div>{closedNow?<div className="customer-closure"><strong>📣 ร้านปิดชั่วคราว</strong><p>{closure?.reason||"ร้านหยุดให้บริการชั่วคราว"}{closure?.reopensOn?` · กลับมาเปิด ${closure.reopensOn}`:""}</p></div>:null}{shop?.description?<p className="customer-shop-desc">{shop.description}</p>:null}{shop?.store_hours_enabled&&shop.weekly_hours?.length?<div className="customer-shop-hours"><strong>เวลาเปิด – ปิดร้าน</strong>{shop.weekly_hours.map(day=><span key={day.day}>{day.day}: {day.open?`${day.opensAt} – ${day.closesAt}`:"ปิด"}</span>)}</div>:null}{shop?.contacts?.some(c=>c.active)?<div className="customer-shop-contacts"><strong>ติดต่อร้าน</strong>{shop.contacts.filter(c=>c.active).map(c=><a href={safeContactUrl(c.url)} key={c.id} target="_blank" rel="noreferrer">{c.label}: {c.value}</a>)}</div>:null}<div className="customer-actions"><button onClick={()=>setTab("card")}><CreditCard/>บัตรสมาชิก</button><button onClick={()=>setTab("coupons")}><TicketPercent/>คูปองของฉัน</button><button onClick={()=>setTab("news")}><Newspaper/>ข่าวสาร</button></div></>}
{tab==="card"&&(loggedIn?<><h2>ตัวอย่างบัตรสมาชิก</h2><MemberCard design={normalizeCardDesign(shop?.card_design)} member={{name:"บัตรตัวอย่าง",code:"DEMO-ONLY",level:"Member",points:0,spending:0}} shopName={shop?.shop_name_en||"TAMMY PET SHOP"}/><p className="point-note">แตะบัตรเพื่อพลิกดู QR · ยังไม่เชื่อมข้อมูลสมาชิกจริง จึงไม่สามารถใช้ QR ตัวอย่างให้แต้มได้</p></>:<LoginCard submit={login}/>) }
{tab==="news"&&<><h2>ข่าวสารและโปรโมชั่น</h2><div className="portal-list">{popupItems.filter(item=>item.source==="news").map(item=><Link className="portal-content-link" href={`/customer/content/${encodeURIComponent(item.source+":"+item.id)}`} key={item.id}>{item.image?<Image src={item.image} alt="" width={52} height={52} unoptimized/>:<Newspaper size={32}/>}<span><strong>{item.title}</strong><small>{item.summary}</small></span></Link>)}</div></>}
{tab==="coupons"&&<><h2>คูปองของฉัน</h2>{!loggedIn&&<p className="portal-hint">เข้าสู่ระบบเพื่อเก็บและใช้คูปอง</p>}<div className="coupon-stack">{coupons.map(c=><article className={c.color} key={c.code}><Gift/><div><h3>{c.title}</h3><p>{c.detail}</p><code>{c.code}</code></div><button onClick={()=>loggedIn?setMessage(`เก็บคูปอง ${c.code} แล้ว`):setTab("account")}>{loggedIn?"เก็บคูปอง":"เข้าสู่ระบบ"}</button></article>)}</div></>}
{tab==="account"&&(loggedIn?<div className="portal-profile"><UserRound/><h2>คุณสมาชิก</h2><p>เบอร์โทรศัพท์ที่ลงทะเบียน</p><button onClick={()=>{setLoggedIn(false);setMessage("ออกจากระบบแล้ว")}}>ออกจากระบบ</button></div>:<LoginCard submit={login}/>)}</section>
<nav className="customer-nav">{([["home","หน้าหลัก",Home],["card","บัตรสมาชิก",CreditCard],["news","ข่าวสาร",Newspaper],["coupons","คูปอง",TicketPercent],["account","บัญชี",UserRound]] as const).map(([id,label,Icon])=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}><Icon/><span>{label}</span></button>)}</nav>{popupOpen&&popupEnabled&&popupItems.length?<CustomerPopupCarousel items={popupItems} close={()=>setPopupOpen(false)}/>:null}</main>}
function LoginCard({submit}:{submit:(data:FormData)=>void}){return <form action={submit} className="customer-login"><span><LogIn/></span><h2>ทดลองดูบัตรสมาชิก</h2><p>หน้านี้ยังเป็นตัวอย่าง ยังไม่ตรวจสอบบัญชีสมาชิกจริง</p><label>เบอร์โทรศัพท์<input name="phone" inputMode="tel" placeholder="08x-xxx-xxxx" required/></label><label>PIN 4 หลัก<input name="pin" inputMode="numeric" maxLength={4} placeholder="••••" required/></label><button>ดูบัตรตัวอย่าง</button><small>บัตรตัวอย่างและ QR ยังใช้ให้แต้มไม่ได้</small></form>}
