export type MemberRow = { dog_count?: number | null; cat_count?: number | null; id: string; owner_id: string; member_code: string; member_number?: number; previous_member_code?: string | null; legacy_member_code?: string | null; former_member_code?: string | null; name: string; phone: string | null; email: string | null; birth_date?: string | null; level: "Platinum" | "Gold" | "Silver" | "Member"; points: number; spending: number; last_visit: string | null; status: "active" | "inactive"; newsletter_opt_in: boolean; notes: string; tags: string[]; created_at: string; updated_at: string };
export type MemberTagDefinition = { id: string; owner_id: string; name: string; color: "coral" | "sky" | "mint" | "lavender" | "honey"; created_at: string };
export type PetRow = { id: string; owner_id: string; member_id: string; name: string; species: "cat" | "dog" | "other"; breed: string | null; sex: "male" | "female" | "unknown" | null; birth_date: string | null; allergies: string[]; health_note: string; created_at: string; updated_at: string };
type PointsRow = { id: string; owner_id: string; member_id: string; sale_amount: number; points_delta: number; transaction_type: "earn" | "redeem" | "adjustment"; note: string; created_at: string };
export type Database = { public: { Tables: {
  members: { Row: MemberRow; Insert: Omit<MemberRow, "id" | "owner_id" | "created_at" | "updated_at"> & Partial<Pick<MemberRow, "id" | "owner_id" | "created_at" | "updated_at">>; Update: Partial<Omit<MemberRow, "id" | "owner_id" | "created_at">>; Relationships: [] };
  pets: { Row: PetRow; Insert: Omit<PetRow, "id" | "owner_id" | "created_at" | "updated_at"> & Partial<Pick<PetRow, "id" | "owner_id" | "created_at" | "updated_at">>; Update: Partial<Omit<PetRow, "id" | "owner_id" | "created_at">>; Relationships: [] };
  points_transactions: { Row: PointsRow; Insert: Omit<PointsRow, "id" | "owner_id" | "created_at"> & Partial<Pick<PointsRow, "id" | "owner_id" | "created_at">>; Update: Partial<Omit<PointsRow, "id" | "owner_id" | "created_at">>; Relationships: [] };
}; Views: Record<string, never>; Functions: Record<string, never>; Enums: Record<string, never>; CompositeTypes: Record<string, never> } };
