alter table public.members alter column owner_id drop not null;
alter table public.pets alter column owner_id drop not null;
alter table public.points_transactions alter column owner_id drop not null;

create table public.rewards (id uuid primary key default gen_random_uuid(), owner_id uuid default auth.uid() references auth.users(id) on delete cascade, title text not null, description text not null default '', points_cost integer not null default 0 check(points_cost>=0), stock integer check(stock is null or stock>=0), image_url text, active boolean not null default true, starts_at timestamptz, ends_at timestamptz, popup_enabled boolean not null default false, popup_order integer not null default 1, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), check(ends_at is null or starts_at is null or ends_at>=starts_at));
create table public.coupons (id uuid primary key default gen_random_uuid(), owner_id uuid default auth.uid() references auth.users(id) on delete cascade, code text not null, title text not null, description text not null default '', discount_type text not null check(discount_type in ('percent','fixed')), discount_value numeric(12,2) not null check(discount_value>0), min_spend numeric(12,2) not null default 0, usage_limit integer, used_count integer not null default 0, active boolean not null default true, starts_at timestamptz, ends_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique nulls not distinct(owner_id,code), check(discount_type<>'percent' or discount_value<=100));
create table public.news (id uuid primary key default gen_random_uuid(), owner_id uuid default auth.uid() references auth.users(id) on delete cascade, title text not null, summary text not null default '', content text not null default '', image_url text, status text not null default 'draft' check(status in ('draft','published','archived')), published_at timestamptz, popup_enabled boolean not null default false, popup_order integer not null default 1, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.redemptions (id uuid primary key default gen_random_uuid(), owner_id uuid default auth.uid() references auth.users(id) on delete cascade, member_id uuid not null references public.members(id) on delete restrict, reward_id uuid references public.rewards(id) on delete restrict, coupon_id uuid references public.coupons(id) on delete restrict, points_spent integer not null default 0, status text not null default 'completed' check(status in ('pending','completed','cancelled')), note text not null default '', redeemed_at timestamptz not null default now(), check(num_nonnulls(reward_id,coupon_id)=1));
create table public.store_settings (owner_id uuid primary key default auth.uid() references auth.users(id) on delete cascade, shop_name text not null default 'แทมมี่อาหารสัตว์', shop_name_en text not null default 'Tammy Pet Shop', description text not null default '', welcome_message text not null default '', logo_url text, login_image_url text, points_spend integer not null default 100, points_earned integer not null default 1, promotion_multiplier integer not null default 1, point_expiry_months integer, opening_time time, closing_time time, extra jsonb not null default '{}', updated_at timestamptz not null default now());
create table public.contact_channels (id uuid primary key default gen_random_uuid(), owner_id uuid default auth.uid() references auth.users(id) on delete cascade, platform text not null check(platform in ('line','facebook','instagram','tiktok','youtube','phone','website')), label text not null, value text not null, url text, active boolean not null default true, sort_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.audit_logs (id bigint generated always as identity primary key, owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade, actor_id uuid not null default auth.uid() references auth.users(id), action text not null, entity_type text not null, entity_id text, details jsonb not null default '{}', created_at timestamptz not null default now());

create index rewards_owner_active_idx on public.rewards(owner_id,active,created_at desc); create index coupons_owner_active_idx on public.coupons(owner_id,active,created_at desc); create index news_owner_status_idx on public.news(owner_id,status,published_at desc); create index redemptions_owner_member_idx on public.redemptions(owner_id,member_id,redeemed_at desc); create index redemptions_reward_idx on public.redemptions(reward_id); create index redemptions_coupon_idx on public.redemptions(coupon_id); create index contacts_owner_sort_idx on public.contact_channels(owner_id,sort_order); create index audit_owner_created_idx on public.audit_logs(owner_id,created_at desc);

do $$ declare t text; begin foreach t in array array['rewards','coupons','news','redemptions','store_settings','contact_channels','audit_logs'] loop execute format('alter table public.%I enable row level security',t); execute format('create policy %I on public.%I for select to authenticated using ((select auth.uid())=owner_id)',t||'_select_own',t); execute format('create policy %I on public.%I for insert to authenticated with check ((select auth.uid())=owner_id)',t||'_insert_own',t); if t<>'audit_logs' then execute format('create policy %I on public.%I for update to authenticated using ((select auth.uid())=owner_id) with check ((select auth.uid())=owner_id)',t||'_update_own',t); execute format('create policy %I on public.%I for delete to authenticated using ((select auth.uid())=owner_id)',t||'_delete_own',t); end if; end loop; end $$;
revoke all on public.rewards,public.coupons,public.news,public.redemptions,public.store_settings,public.contact_channels,public.audit_logs from anon;
grant select,insert,update,delete on public.rewards,public.coupons,public.news,public.redemptions,public.store_settings,public.contact_channels to authenticated; grant select,insert on public.audit_logs to authenticated;

create function public.claim_starter_data() returns boolean language plpgsql security definer set search_path='' as $$ declare u uuid:=(select auth.uid()); begin if u is null then raise exception 'Authentication required'; end if; perform pg_advisory_xact_lock(77190421); if exists(select 1 from public.members where owner_id=u) then return false; end if; if not exists(select 1 from public.members where owner_id is null) then return false; end if; update public.members set owner_id=u where owner_id is null; update public.pets set owner_id=u where owner_id is null; update public.points_transactions set owner_id=u where owner_id is null; update public.rewards set owner_id=u where owner_id is null; update public.coupons set owner_id=u where owner_id is null; update public.news set owner_id=u where owner_id is null; update public.contact_channels set owner_id=u where owner_id is null; insert into public.store_settings(owner_id,description,welcome_message,opening_time,closing_time) values(u,'ร้านอาหารสัตว์ ของเล่น และอุปกรณ์','ยินดีต้อนรับสู่แทมมี่อาหารสัตว์','09:00','20:00') on conflict do nothing; return true; end $$;
revoke all on function public.claim_starter_data() from public,anon; grant execute on function public.claim_starter_data() to authenticated;
create function public.award_points(target_member_id uuid,sale numeric,earned integer,memo text default '') returns public.members language plpgsql security definer set search_path='' as $$ declare u uuid:=(select auth.uid()); m public.members; begin if u is null or sale<0 or earned<=0 then raise exception 'Invalid transaction'; end if; update public.members set points=points+earned,spending=spending+sale,last_visit=current_date,updated_at=now() where id=target_member_id and owner_id=u returning * into m; if m.id is null then raise exception 'Member not found'; end if; insert into public.points_transactions(owner_id,member_id,sale_amount,points_delta,transaction_type,note) values(u,target_member_id,sale,earned,'earn',memo); insert into public.audit_logs(owner_id,actor_id,action,entity_type,entity_id,details) values(u,u,'award_points','member',target_member_id::text,jsonb_build_object('sale',sale,'points',earned)); return m; end $$;
revoke all on function public.award_points(uuid,numeric,integer,text) from public,anon; grant execute on function public.award_points(uuid,numeric,integer,text) to authenticated;

insert into public.members(owner_id,member_code,name,phone,email,level,points,spending,last_visit,status,newsletter_opt_in,notes,tags) select null,'TM'||lpad(n::text,6,'0'),names[n], '08'||n||'-234-56'||lpad(n::text,2,'0'), lower('member'||n||'@example.com'), levels[1+((n-1)%3)], pts[n], spend[n],current_date-n,'active',n%2=0,'ข้อมูลตัวอย่างพร้อมแก้ไข',array['ข้อมูลเริ่มต้น'] from generate_series(1,10)n, lateral(select array['คุณรนภัทร วงศ์ศรี','คุณกมลวรรณ ใจดี','คุณศิริภพ พูลทรัพย์','คุณนันทิตา สวัสดิ์ผล','คุณพงศธร รัตนกุล','คุณชลิตา กมลสุข','คุณอรรถพล จันทร์ดี','คุณวิไลลักษณ์ ครองสุข','คุณภัทรวดี เมฆสว่าง','คุณธนพล ศรีสมบัติ'] names,array['Gold','Silver','Member'] levels,array[2480,920,310,1760,640,220,3120,980,415,760] pts,array[61240,12340,4890,36500,9800,3450,82900,17450,6380,15200] spend)x;
insert into public.pets(owner_id,member_id,name,species,breed,sex,birth_date) select null,id,'น้อง'||substring(member_code from 7),'cat','Domestic Shorthair','unknown',current_date-interval '3 years' from public.members where owner_id is null;
insert into public.points_transactions(owner_id,member_id,sale_amount,points_delta,transaction_type,note) select null,id,spending/10,greatest(points/10,1),'earn','ยอดยกมาตัวอย่าง' from public.members where owner_id is null;
insert into public.rewards(owner_id,title,description,points_cost,stock,active,popup_enabled) values(null,'ขนมแมวเลีย 4 ชิ้น','คละรส 4 ชิ้น',500,24,true,true),(null,'ที่นอนนุ่มสำหรับแมว','ขนาด M',800,10,true,false),(null,'ของเล่นลูกบอล','แพ็ก 3 ชิ้น',350,50,true,false);
insert into public.coupons(owner_id,code,title,discount_type,discount_value,min_spend,usage_limit) values(null,'WELCOME10','สมาชิกใหม่ลด 10%','percent',10,500,200),(null,'PET100','ลดทันที 100 บาท','fixed',100,1000,100),(null,'GROOM15','กรูมมิ่งลด 15%','percent',15,0,80);
insert into public.news(owner_id,title,summary,content,status,published_at,popup_enabled) values(null,'โปรพิเศษประจำเดือน','รับแต้มคูณสอง','ช้อปสินค้าที่ร่วมรายการและรับแต้มคูณสอง','published',now(),true),(null,'เคล็ดลับหน้าร้อน','ดูแลน้ำและอุณหภูมิ','เตรียมน้ำสะอาดและมุมพักเย็น','published',now(),false),(null,'สินค้าใหม่เข้าแล้ว','พบกับอาหารสูตรใหม่','พร้อมจำหน่ายเร็ว ๆ นี้','draft',null,false);
insert into public.contact_channels(owner_id,platform,label,value,url,sort_order) values(null,'line','LINE Official Account','@tammypetshop','https://line.me/R/ti/p/@tammypetshop',1),(null,'facebook','Facebook Page','Tammy Pet Shop','https://facebook.com',2),(null,'tiktok','TikTok','@tammypetshop','https://www.tiktok.com/@tammypetshop',3),(null,'phone','โทรศัพท์','02-123-4567','tel:021234567',4);
