"use client";
import { useEffect, useRef, useState } from "react";
import { Camera, Maximize, PawPrint, Play, RotateCcw } from "lucide-react";
import { GameStage, type StageSpin } from "./game-stage";
import type { PublicPrize } from "@/lib/games/types";
export type SceneView={ camera:"front"|"close"; lighting:"warm"|"day"; pets:boolean };
export const defaultSceneView:SceneView={camera:"front",lighting:"warm",pets:true};
export function AdminGamePreview({prizes,view,onView}:{prizes:PublicPrize[];view:SceneView;onView:(view:SceneView)=>void}){
  const root=useRef<HTMLElement>(null),[spin,setSpin]=useState<StageSpin|null>(null),[busy,setBusy]=useState(false),[version,setVersion]=useState(0),[result,setResult]=useState("");
  useEffect(()=>{setSpin(null);setBusy(false);setResult("");},[prizes,view.camera,view.lighting,view.pets]);
  const test=()=>{if(busy||!prizes.length)return;const random=new Uint32Array(1);crypto.getRandomValues(random);const prize=prizes[random[0]%prizes.length];setResult(prize.title);setBusy(true);setSpin({key:crypto.randomUUID(),targetId:prize.id});};
  return <aside ref={root} className="game-preview game-studio-preview"><header><h2><PawPrint size={21}/>ตัวอย่างเกม</h2><div className="game-preview-tools"><label><Camera size={16}/><select aria-label="มุมกล้องตัวอย่าง" disabled={busy} value={view.camera} onChange={e=>onView({...view,camera:e.target.value as SceneView["camera"]})}><option value="front">มุมกล้อง</option><option value="close">ใกล้วงล้อ</option></select></label><button aria-label="ดูตัวอย่างเต็มจอ" onClick={()=>void root.current?.requestFullscreen().catch(()=>setResult("เบราว์เซอร์นี้ไม่รองรับเต็มจอ"))}><Maximize size={17}/></button></div></header><div className="game-phone-frame"><div className="game-phone-screen"><div className="game-phone-status"><span>9:41</span><i aria-hidden="true"/><span>▮▮▮ ▰</span></div><div className="game-phone-heading"><small>TAMMY PLAY CLUB · โหมดทดลอง</small><h3>วงล้ออุ้งเท้า</h3><p>ลองหมุนก่อนเปิดกิจกรรมจริง</p></div><div className="game-preview-stage"><button className="game-preview-reset" disabled={busy} title="เริ่มตัวอย่างใหม่" onClick={()=>{setVersion(v=>v+1);setSpin(null);setResult("");}}><RotateCcw size={18}/></button>{prizes.length?<GameStage key={version} prizes={prizes} spin={spin} onFinish={()=>setBusy(false)} view={view}/>:<div className="game-stage-loading">เปิดอย่างน้อย 1 ช่องเพื่อดูตัวอย่าง</div>}</div><footer><button className="paw-spin" disabled={busy||!prizes.length} onClick={test}><PawPrint/>{busy?"กำลังหมุนตัวอย่าง…":"ทดลองหมุนวงล้อ"}<Play size={17}/></button><p>{!busy&&spin?`ผลทดลอง: ${result} · ไม่ใช่โอกาสออกจริง`:"ทดสอบภาพและการหมุน · ไม่หักสิทธิ์ ไม่แจกของจริง"}</p></footer><div className="game-phone-home" aria-hidden="true"/></div></div><p className="game-phone-caption">iPhone 18 Pro Max · สัดส่วนหน้าจอ 1320 × 2868<br/>ย่อเฉพาะเมื่อพื้นที่ไม่พอ</p></aside>;
}
