"use client";
import { Children, isValidElement, useEffect, useRef, useState, type SelectHTMLAttributes, type ChangeEvent } from "react";
import { Check, ChevronDown } from "lucide-react";
export function GameSelect({children,value,onChange,disabled,...rest}:SelectHTMLAttributes<HTMLSelectElement>){
 const [open,setOpen]=useState(false);const root=useRef<HTMLDivElement>(null);
 const options=Children.toArray(children).filter(isValidElement).map(child=>{const p=child.props as {value:string;children:string;disabled?:boolean};return p;});
 useEffect(()=>{const close=(event:PointerEvent)=>{if(!root.current?.contains(event.target as Node))setOpen(false);};document.addEventListener("pointerdown",close);return()=>document.removeEventListener("pointerdown",close);},[]);
 return <div className="game-pretty-select" ref={root}><button type="button" disabled={disabled} aria-label={rest["aria-label"]||"เลือกตัวเลือก"} aria-haspopup="listbox" aria-expanded={open} onClick={()=>setOpen(!open)} onKeyDown={e=>{if(e.key==="Escape")setOpen(false);if(e.key==="ArrowDown"){e.preventDefault();setOpen(true);requestAnimationFrame(()=>root.current?.querySelector<HTMLButtonElement>('[role="option"]')?.focus());}}}>{options.find(o=>String(o.value)===String(value))?.children}<ChevronDown size={15}/></button>{open&&<div className="game-select-options" role="listbox" onKeyDown={e=>{if(e.key==="Escape"){setOpen(false);root.current?.querySelector("button")?.focus();}if(e.key==="ArrowDown"||e.key==="ArrowUp"){e.preventDefault();const buttons=Array.from(e.currentTarget.querySelectorAll<HTMLButtonElement>("button:not(:disabled)"));const index=buttons.indexOf(document.activeElement as HTMLButtonElement);buttons[(index+(e.key==="ArrowDown"?1:-1)+buttons.length)%buttons.length]?.focus();}}}>{options.map(o=><button type="button" role="option" disabled={o.disabled} aria-selected={String(value)===String(o.value)} key={String(o.value)} onClick={()=>{onChange?.({target:{value:o.value},currentTarget:{value:o.value}} as ChangeEvent<HTMLSelectElement>);setOpen(false);root.current?.querySelector("button")?.focus();}}>{o.children}{String(value)===String(o.value)&&<Check size={14}/>}</button>)}</div>}</div>;
}
