"use client";
import { notifyCatalogChanged } from "@/lib/catalog-live";
import {useEffect,useRef,useState} from "react";
import {Search,Ticket,X,Check,ScanLine} from "lucide-react";
import {ProfilePhoto} from "../profile-photo";
import {supabase} from "@/lib/supabase/client";
import { crmOwnerId } from "@/lib/supabase/crm-data";
import { cachedTicketMembers,preloadTicketMembers,findTicketMembers,type TicketMember as Member } from "@/lib/games/ticket-members";
import { normalizeMemberScan,normalizeCouponScan,normalizeGameScan } from "@/lib/member-code";
import { MemberQrScanner } from "../member-qr-scanner";
export function GameTicketDialog({onClose,ready}:{onClose:()=>void;ready:boolean}){
 const [query,setQuery]=useState(""),[members,setMembers]=useState<Member[]>(()=>cachedTicketMembers(crmOwnerId()||"")),[selected,setSelected]=useState<Member|null>(null),[amount,setAmount]=useState(1),[note,setNote]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(""),[success,setSuccess]=useState("");
 const [scanning,setScanning]=useState(false),[scanError,setScanError]=useState("");const scanRequest=useRef<AbortController|null>(null);
 const pending=useRef<{id:string;memberId:string;amount:number;note:string}|null>(null);const searchRef=useRef<HTMLInputElement>(null);const dialogRef=useRef<HTMLElement>(null);
 useEffect(()=>{if(scanning)return;const previous=document.activeElement as HTMLElement|null;searchRef.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==="Escape"&&!busy)onClose();if(e.key==="Tab"){const items=Array.from(dialogRef.current?.querySelectorAll<HTMLElement>("button:not(:disabled),input:not(:disabled)")||[]);const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener("keydown",key);return()=>{document.removeEventListener("keydown",key);previous?.focus();};},[onClose,busy,scanning]);
  useEffect(()=>{const abort=new AbortController();const term=query.trim();setLoading(true);setError("");if(!term){setMembers(cachedTicketMembers(crmOwnerId()||""));void preloadTicketMembers(crmOwnerId()||"").then(rows=>{if(!abort.signal.aborted)setMembers(rows.slice(0,3));}).catch(e=>{if(!abort.signal.aborted)setError(e.message);}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});return()=>abort.abort();}
 const local=cachedTicketMembers(crmOwnerId()||"").filter(m=>[m.name,m.phone,m.member_code].some(v=>(v||"").toLowerCase().includes(term.toLowerCase())));setMembers(local);const timer=setTimeout(()=>{void findTicketMembers(term,abort.signal).then(rows=>{if(!abort.signal.aborted)setMembers(rows);}).catch(e=>{if(!abort.signal.aborted)setError(e.message);}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});},180);return()=>{abort.abort();clearTimeout(timer);};},[query]);
 useEffect(()=>()=>scanRequest.current?.abort(),[]);
 const scanMember=(raw:string)=>{if(normalizeGameScan(raw)||normalizeCouponScan(raw)){setScanError("กรุณาสแกนรหัสสมาชิกเพื่อเลือกผู้รับสิทธิ์");return false;}const code=normalizeMemberScan(raw);if(!code){setScanError("ไม่พบรหัสสมาชิกใน QR นี้");return false;}setScanning(false);setError("");scanRequest.current?.abort();const abort=new AbortController();scanRequest.current=abort;void findTicketMembers("",abort.signal,code).then(rows=>{if(!abort.signal.aborted){if(!rows.length){setError("ไม่พบสมาชิกจากรหัสที่สแกน");return;}setSelected(rows[0]);setSuccess("");setQuery(rows[0].member_code);setMembers(rows);}}).catch(e=>{if(!abort.signal.aborted)setError(e.message);});return true;};
const give=async()=>{if(!selected||busy||!Number.isInteger(amount)||amount<1||amount>10000)return;setBusy(true);setError("");setSuccess("");try{if(!ready)throw new Error("ยังให้สิทธิ์จริงไม่ได้ ต้องเปิดใช้ฐานข้อมูลเกมก่อน");if(!pending.current||pending.current.memberId!==selected.id||pending.current.amount!==amount||pending.current.note!==note)pending.current={id:crypto.randomUUID(),memberId:selected.id,amount,note};const session=await supabase?.auth.getSession();if(!session?.data.session)throw new Error("กรุณาเข้าสู่ระบบ");const response=await fetch("/api/admin/games",{method:"POST",headers:{Authorization:`Bearer ${session.data.session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({action:"tickets",memberId:selected.id,requestId:pending.current.id,amount,note})});const json=await response.json();if(!response.ok)throw new Error(json.error||"ให้สิทธิ์ไม่สำเร็จ");notifyCatalogChanged();setSuccess(`ให้ ${selected.name} ${amount} สิทธิ์ทดสอบแล้ว · คงเหลือ ${json.result.balance} ครั้ง`);pending.current=null;setSelected(null);setAmount(1);setNote("");}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 if(scanning)return <MemberQrScanner onScan={scanMember} onClose={()=>setScanning(false)} error={scanError}/>;
 return <div className="preview-modal game-ticket-modal" role="dialog" aria-modal="true" aria-labelledby="game-ticket-title"><button className="preview-backdrop" aria-label="ปิด" disabled={busy} onClick={onClose}/><section ref={dialogRef}><button className="preview-close" aria-label="ปิด" disabled={busy} onClick={onClose}><X/></button><h2 id="game-ticket-title"><Ticket size={23}/>ให้สิทธิ์ทดสอบ</h2><p>สิทธิ์ชั่วคราว 1 ชั่วโมง · ไม่เพิ่มสิทธิ์สะสมจากยอดซื้อ</p>{success&&<p className="game-ticket-success" role="status"><Check size={17}/>{success}</p>}<div className="game-ticket-search"><Search size={18}/><input ref={searchRef} value={query} disabled={busy} onChange={e=>setQuery(e.target.value)} placeholder="ค้นหาชื่อ / เบอร์โทร / รหัสสมาชิก" aria-label="ค้นหาสมาชิก"/><button type="button" className="game-ticket-scan" aria-label="สแกนรหัสสมาชิก" title="สแกนสมาชิก" disabled={busy} onClick={()=>{setScanError("");setScanning(true);}}><ScanLine size={19}/></button></div><div className="game-ticket-members" aria-label="รายชื่อสมาชิก" aria-busy={loading}>{!members.length&&!loading?<p>ไม่พบสมาชิก ลองค้นหาหรือสแกนรหัส</p>:members.map(m=><button type="button" disabled={busy} key={m.id} className={selected?.id===m.id?"selected":""} aria-pressed={selected?.id===m.id} onClick={()=>{setSelected(m);setSuccess("");}}><ProfilePhoto src={m.line_picture_url} size={40} alt={`รูปโปรไฟล์ของ ${m.name}`}/><span><strong>{m.name}</strong><small>{m.member_code} · {m.phone}</small></span>{selected?.id===m.id&&<Check size={17}/>}</button>)}</div><p className="game-test-warning">เล่นด้วยสิทธิ์ทดสอบได้รับรางวัลจริง และตัดสต็อกจริง</p><div className="game-ticket-fields"><label>จำนวนสิทธิ์<input type="number" min={1} max={10000} step={1} value={amount} disabled={busy} onChange={e=>setAmount(Number(e.target.value))}/></label><label>หมายเหตุ<input value={note} maxLength={200} disabled={busy} placeholder="เช่น กิจกรรมพิเศษ" onChange={e=>setNote(e.target.value)}/></label></div>{error&&<p className="paw-alert" role="alert">{error}</p>}{!ready&&<p className="game-note">ค้นหาและเลือกสมาชิกได้ · รอเปิดฐานข้อมูลก่อนให้สิทธิ์จริง</p>}<button className="paw-primary" disabled={!selected||busy||!Number.isInteger(amount)||amount<1||amount>10000} onClick={()=>void give()}><Ticket size={17}/>{busy?"กำลังให้สิทธิ์…":`ให้ ${amount||0} สิทธิ์ทดสอบ`}</button></section></div>;
}
