"use client";
import Link from "next/link";
import { GameHistory } from "./game-history";
import { GameRewardCheck } from "./game-reward-check";
import { GameSelect } from "./game-select";
import { useEffect, useMemo, useState } from "react";
import { Check, Gift, Plus, Save, Trash2, Ticket, Menu, Settings2, Gamepad2, History, ShieldCheck, PawPrint, LockKeyhole } from "lucide-react";
import { Sidebar } from "@/components/sidebar";
import { supabase } from "@/lib/supabase/client";
import { defaultGameSetup, newPrize, publicPrize, validateSetup } from "@/lib/games/config";
import type { AdminPrize, GamePlay, GameSetup, PublicPrize } from "@/lib/games/types";
import { PASTEL_PRIZE_COLORS, randomPrizeColors } from "@/lib/games/pastel-colors";
import { CouponQrScanner } from "../coupon-qr-scanner";
import { AdminGamePreview,defaultSceneView,type SceneView } from "./admin-game-preview";
type HistoryPlay=GamePlay&{member_id:string};
type Member={id:string;name:string;line_picture_url:string|null};
type Inspection={grant:{id:string;title:string;kind:string;status:string;expires_at:string;snapshot:PublicPrize};member:{name:string;line_picture_url:string|null}};
export function GamesManager({preview=false,initialGameKey="paw-wheel",activityView}:{preview?:boolean;initialGameKey?:string;activityView?:"history"|"claim"}){
  const [setup,setSetup]=useState<GameSetup>(defaultGameSetup),[ready,setReady]=useState(preview),[editable,setEditable]=useState(preview),[showConfig,setShowConfig]=useState(preview),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[tab,setTab]=useState(activityView||"settings"),[menu,setMenu]=useState(false),[plays,setPlays]=useState<HistoryPlay[]>([]),[members,setMembers]=useState<Member[]>([]),[token,setToken]=useState(""),[inspection,setInspection]=useState<Inspection|null>(null),[sale,setSale]=useState(0),[scanning,setScanning]=useState(false),[choices,setChoices]=useState<{game_key:string;name:string}[]>([]);
  const [view,setView]=useState<SceneView>(defaultSceneView);
  const api=async(body?:object,gameKey="paw-wheel")=>{const session=await supabase?.auth.getSession();if(!session?.data.session)throw new Error("กรุณาเข้าสู่ระบบ");const response=await fetch(`/api/admin/games?game=${encodeURIComponent(gameKey)}`,{method:body?"POST":"GET",headers:{Authorization:`Bearer ${session.data.session.access_token}`,"Content-Type":"application/json"},...(body?{body:JSON.stringify(body)}:{}),cache:"no-store"});const json=await response.json();if(!response.ok)throw new Error(json.error||"เชื่อมต่อไม่สำเร็จ");return json;};
  const load=async(gameKey=initialGameKey==="new"?"paw-wheel":initialGameKey)=>{if(preview){setMessage("หน้านี้เป็นตัวอย่าง ไม่ดึงข้อมูลสมาชิกจริง");return;}const json=await api(undefined,gameKey);setChoices(json.choices||[]);setReady(json.ready);setEditable(json.canEdit);setShowConfig(Boolean(json.setup));if(json.setup){if(!json.ready&&initialGameKey!=="new"){try{const saved=localStorage.getItem(`tammy-game-draft:${gameKey}`);if(saved){const draft=JSON.parse(saved);validateSetup(draft);json.setup=draft;}}catch{setMessage("อ่านร่างไม่ได้ กรุณาตั้งค่าใหม่");}}if(initialGameKey==="new"&&gameKey==="paw-wheel"){const program=json.setup.program;json.setup=defaultGameSetup();json.setup.program=program;json.setup.game.key=`wheel-${crypto.randomUUID().slice(0,8)}`;json.setup.game.name="วงล้อกิจกรรมใหม่";}const originalColors=json.setup.game.prizes.map((p:AdminPrize)=>p.color.toLowerCase());const colors=new Set(originalColors).size===originalColors.length&&originalColors.every((c:string)=>PASTEL_PRIZE_COLORS.includes(c))?originalColors:randomPrizeColors(json.setup.game.prizes.length);setSetup({...json.setup,game:{...json.setup.game,prizes:json.setup.game.prizes.map((p:AdminPrize,i:number)=>({...p,color:colors[i]}))}});}else setTab(activityView||"claim");setPlays(json.plays||[]);setMembers(json.members||[]);};
  useEffect(()=>{if(!preview)void load().catch(e=>setMessage(e.message));else setSetup(s=>{const colors=randomPrizeColors(s.game.prizes.length);return {...s,game:{...s.game,prizes:s.game.prizes.map((p,i)=>({...p,color:colors[i]}))}};});},[preview,initialGameKey]);
  const change=(id:string,patch:Partial<AdminPrize>)=>setSetup(s=>({...s,game:{...s.game,prizes:s.game.prizes.map(p=>p.id===id?{...p,...patch}:p)}}));
  const total=setup.game.prizes.filter(p=>p.active).reduce((s,p)=>s+p.weight,0);
  const save=async()=>{if(busy)return;setBusy(true);setMessage("");try{validateSetup(setup);if(!ready&&!preview){localStorage.setItem(`tammy-game-draft:${setup.game.key}`,JSON.stringify(setup));throw new Error("เก็บร่างในเครื่องนี้แล้ว · ยังบันทึกเข้าร้านไม่ได้ เพราะฐานข้อมูลเกมยังไม่เปิดใช้")};if(preview){setMessage("ตรวจตัวอย่างผ่านแล้ว หน้านี้ไม่บันทึกข้อมูลจริง");return;}const json=await api({action:"save",setup});setSetup(json.setup);setReady(json.ready);setMessage("บันทึกกิจกรรมแล้ว");await load(json.setup.game.key);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}};
  const upload=async(id:string,file?:File)=>{if(!file)return;if(!file.type.startsWith("image/")){setMessage("เลือกรูปภาพเท่านั้น");return;}try{const bitmap=await createImageBitmap(file);const canvas=document.createElement("canvas");const scale=Math.min(1,420/Math.max(bitmap.width,bitmap.height));canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext("2d")!.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const image=canvas.toDataURL("image/webp",.8);if(image.length>300000)throw new Error("ภาพใหญ่เกินไป กรุณาเลือกรูปใหม่");change(id,{image});}catch(e){setMessage((e as Error).message);}};
  const inspect=async()=>{setBusy(true);setInspection(null);try{const json=await api({action:"inspect",token});setInspection(json);setMessage("");}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}};
  const redeem=async()=>{if(!inspection||busy)return;setBusy(true);try{await api({action:"redeem",token,saleAmount:sale});setInspection(s=>s?{...s,grant:{...s.grant,status:"used"}}:null);setMessage("ยืนยันใช้รางวัลแล้ว");await load();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}};
  const shown=useMemo(()=>setup.game.prizes.filter(p=>p.active).map(publicPrize),[setup.game.prizes]);
  const activityPanels=<>
    {tab==="history"&&<GameHistory plays={plays} members={members} preview={preview} canClear={editable} onCleared={()=>{setPlays([]);void load().catch(e=>setMessage(e.message));}}/>}
    {tab==="claim"&&<GameRewardCheck preview={preview}/>}
  </>;
  if(activityView)return <div className="game-shared-activity">{message&&<p className="paw-alert" role="status">{message}</p>}{!ready&&<p className="paw-alert">ฐานข้อมูลเกมยังไม่พร้อมใช้งาน</p>}{activityPanels}{scanning&&<CouponQrScanner onClose={()=>setScanning(false)}/>}</div>;
  return <div className="app-shell game-admin-shell"><div className={`sidebar-wrap${menu?" open":""}`}><Sidebar activePath="/games" preview={preview} onClose={()=>setMenu(false)}/></div><main className="game-admin"><header className="game-admin-header"><div><button className="game-menu" aria-label="เปิดเมนู" onClick={()=>setMenu(true)}><Menu/></button><Link className="game-back-link" href="/games">← กลับหน้าเกมทั้งหมด</Link><h1><span className="game-title-icon"><PawPrint/></span>{setup.game.name}</h1></div>{showConfig&&<label className={`game-header-toggle ${setup.game.enabled?"is-on":"is-off"}`}><input type="checkbox" disabled={!editable||busy} checked={setup.game.enabled} onChange={e=>setSetup(s=>({...s,game:{...s.game,enabled:e.target.checked}}))}/><span>{setup.game.enabled?"เปิดใช้งาน":"ปิดใช้งาน"}<small>{ready?"บันทึกเพื่อยืนยันสถานะ":"สถานะร่าง · ยังไม่เปิดจริง"}</small></span></label>}{showConfig&&<button className="paw-primary" disabled={!editable||busy} onClick={()=>void save()}><Save size={18}/>{busy?"กำลังบันทึก…":"บันทึกกิจกรรม"}</button>}</header>
    {preview&&<div className="game-demo-banner">โหมดตัวอย่าง · ไม่บันทึกหรือแจกของจริง</div>}{!ready&&<div className="paw-alert">ฐานข้อมูลเกมยังไม่พร้อม · แก้ไขร่างและทดลองได้ แต่ยังบันทึกหรือแจกของจริงไม่ได้</div>}
    {message&&<div className="paw-alert" role="status">{message}<button onClick={()=>void load().catch(e=>setMessage(e.message))}>อัปเดตข้อมูล</button></div>}
    {tab==="settings"&&showConfig&&<div className="game-editor"><div className="game-settings-column"><label className="game-name-field">ชื่อเกม<input disabled={!editable||busy} value={setup.game.name} maxLength={80} onChange={e=>setSetup(s=>({...s,game:{...s.game,name:e.target.value}}))}/></label>
<section className="game-panel"><div className="game-panel-title"><Gift size={20}/><div><h2>ตั้งค่ารางวัล</h2><p>กำหนดของรางวัล เรทการออก และจำนวนคงเหลือ</p></div><b className={total>0?"game-total":"game-total invalid"}>รวมเรท {total.toLocaleString("th-TH",{maximumFractionDigits:2})}</b></div><fieldset disabled={!editable||busy}><div className="game-prize-list">{setup.game.prizes.map((p,index)=><article className={`game-prize-editor game-prize-kind-${p.kind}${p.active?"":" is-paused"}`} style={{"--slot-color":p.color} as import("react").CSSProperties} key={p.id}><div className="game-prize-category"><span>{p.kind==="points"?"แต้มสมาชิก":p.kind==="coupon"?"คูปองส่วนลด":"สินค้า / ของขวัญ"}</span><small>ช่อง {index+1}{!p.active&&" · พักช่องนี้"}</small></div><div className="game-prize-heading"><div className="game-prize-quick"><label>เรทการออก<input aria-label={`เรทการออกช่อง ${index+1}`} type="number" min={0} max={100000} step="0.01" value={p.weight} onChange={e=>change(p.id,{weight:Number(e.target.value)})}/></label><label>สต็อก<input aria-label={`สต็อกช่อง ${index+1}`} type="number" min={0} placeholder="∞" value={p.stock??""} onChange={e=>change(p.id,{stock:e.target.value===""?null:Number(e.target.value)})}/></label></div><label className="game-image-picker" style={{background:p.color}}>{p.image?<img src={p.image} alt="รูปของรางวัล"/>:<span>{p.kind==="points"?"🪙":p.kind==="coupon"?"🎟️":"🎁"}</span>}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>void upload(p.id,e.target.files?.[0])}/><small>เปลี่ยนรูป</small></label><div><small>ช่อง {index+1}</small><input aria-label="ชื่อรางวัล" value={p.title} maxLength={100} onChange={e=>change(p.id,{title:e.target.value})}/></div><button className="game-delete" aria-label="ลบช่องรางวัล" disabled={setup.game.prizes.length<=2} onClick={()=>setSetup(s=>({...s,game:{...s.game,prizes:s.game.prizes.filter(x=>x.id!==p.id)}}))}><Trash2 size={17}/></button></div><div className="game-prize-settings"><div className="game-fields"><label>ประเภทรางวัล<GameSelect value={p.kind} onChange={e=>change(p.id,{kind:e.target.value as AdminPrize["kind"]})}><option value="points">แต้มสมาชิก</option><option value="coupon">คูปองส่วนลด</option><option value="item">สินค้า / ของขวัญ</option></GameSelect></label><div className="game-auto-color"><span style={{background:p.color}}/>สีช่องอัตโนมัติ · ไม่ซ้ำกัน</div>{p.kind==="points"&&<label>จำนวนแต้ม<input type="number" min={1} max={100000} value={p.points} onChange={e=>change(p.id,{points:Number(e.target.value)})}/></label>}
      <label className={`game-header-toggle game-slot-toggle ${p.active?"is-on":"is-off"}`}><input type="checkbox" role="switch" aria-label={`เปิดช่องรางวัล ${index+1}`} checked={p.active} onChange={e=>change(p.id,{active:e.target.checked})}/><span>{p.active?"เปิดช่องนี้":"ปิดช่องนี้"}</span></label>
      {p.kind==="coupon"&&<><label>รูปแบบส่วนลด<GameSelect value={p.discountType} onChange={e=>change(p.id,{discountType:e.target.value as AdminPrize["discountType"]})}><option value="percent">เปอร์เซ็นต์</option><option value="fixed">จำนวนบาท</option></GameSelect></label><label>มูลค่าส่วนลด<input type="number" min={1} max={p.discountType==="percent"?100:100000} value={p.discountValue} onChange={e=>change(p.id,{discountValue:Number(e.target.value)})}/></label><label>ยอดซื้อขั้นต่ำ (บาท)<input type="number" min={0} value={p.minSpend} onChange={e=>change(p.id,{minSpend:Number(e.target.value)})}/></label><label>ลดสูงสุด (ว่าง = ไม่จำกัด)<input type="number" min={1} value={p.maxDiscount??""} onChange={e=>change(p.id,{maxDiscount:e.target.value===""?null:Number(e.target.value)})}/></label></>}
      {p.kind!=="points"&&<><label>กำหนดหมดอายุ<GameSelect value={p.expiryMode} onChange={e=>change(p.id,{expiryMode:e.target.value as AdminPrize["expiryMode"]})}><option value="hours">นับจากเวลาที่ได้รับ</option><option value="fixed">วันและเวลาที่กำหนด</option></GameSelect></label>{p.expiryMode==="hours"?<label>อายุรางวัล (วัน)<input type="number" min={1} max={365} step={1} value={p.expiryHours/24} onChange={e=>change(p.id,{expiryHours:Number(e.target.value)*24})}/><small className="game-note">หมดอายุหลังได้รับรางวัล {p.expiryHours/24} วัน</small></label>:<label>หมดอายุ (เวลาประเทศไทย)<input type="datetime-local" value={p.expiresAt?new Date(new Date(p.expiresAt).getTime()+7*3600000).toISOString().slice(0,16):""} onChange={e=>change(p.id,{expiresAt:e.target.value?new Date(`${e.target.value}:00+07:00`).toISOString():null})}/></label>}</>}
      </div></div></article>)}</div><button className="game-add" disabled={setup.game.prizes.length>=16} onClick={()=>setSetup(s=>({...s,game:{...s.game,prizes:[...s.game.prizes,{...newPrize(),id:crypto.randomUUID(),color:randomPrizeColors(1,s.game.prizes.map(p=>p.color))[0]}]}}))}><Plus size={18}/>เพิ่มช่องรางวัล</button></fieldset><p className="game-note game-private-note"><LockKeyhole size={15}/>เรทแสดงเฉพาะแอดมิน · สต็อกว่างหมายถึงไม่จำกัด</p><p className="game-note">ตั้งเรทได้อิสระ ไม่ต้องรวม 100 · เรท 20 ออกบ่อยกว่าเรท 10 สองเท่า · เรท 0 ไม่ออก · สุ่มเฉพาะช่องที่ยังมีสต็อกและไม่หมดอายุ</p></section></div>
    <AdminGamePreview prizes={shown} view={view} onView={setView}/></div>}
  {scanning&&<CouponQrScanner onClose={()=>setScanning(false)}/>}</main></div>;
}
