"use client";
import {useEffect,useRef,useState} from "react";
import {History,ArrowUpRight,X,Gift} from "lucide-react";
import {DateRangePicker} from "../date-range-picker";
import {ProfilePhoto} from "../profile-photo";
import {GameHistoryCleanup} from "./game-history-cleanup";
import {GameSelect} from "./game-select";
import {supabase} from "@/lib/supabase/client";
import type {GamePlay} from "@/lib/games/types";
type Row=GamePlay&{member_id:string;member?:{name:string;line_picture_url:string|null}|null};
const bangkokDay=(value:string)=>new Date(Date.parse(value)+7*3600000).toISOString().slice(0,10);
export function GameHistory({plays,members,preview=false,canClear=false,onCleared}:{canClear?:boolean;onCleared?:()=>void;plays:Row[];members:{id:string;name:string;line_picture_url:string|null}[];preview?:boolean}){
 const [mode,setMode]=useState("latest"),[kind,setKind]=useState("all"),[start,setStart]=useState(""),[end,setEnd]=useState(""),[full,setFull]=useState(false),[rows,setRows]=useState<Row[]>([]),[busy,setBusy]=useState(false),[hasMore,setHasMore]=useState(false),[error,setError]=useState("");const abortRef=useRef<AbortController|null>(null);
 const popup=full||mode==="range"&&!!end&&end!==start;
 const local=plays.filter(p=>(kind==="all"||p.prize.kind===kind)&&(mode!=="range"||!start||bangkokDay(p.created_at)>=start&&bangkokDay(p.created_at)<=(end||start))).map(p=>({...p,member:members.find(m=>m.id===p.member_id)}));
 const fetchRows=async(after?:Row)=>{abortRef.current?.abort();const abort=new AbortController();abortRef.current=abort;setBusy(true);setError("");try{if(preview){setRows(local);setHasMore(false);return;}const session=await supabase?.auth.getSession();if(!session?.data.session)throw new Error("กรุณาเข้าสู่ระบบ");const params=new URLSearchParams({kind});if(mode==="range"&&start){params.set("start",start);params.set("end",end||start);}if(after){params.set("before",after.created_at);params.set("id",after.id);}const response=await fetch(`/api/admin/games/history?${params}`,{headers:{Authorization:`Bearer ${session.data.session.access_token}`},signal:abort.signal,cache:"no-store"});const json=await response.json();if(!response.ok)throw new Error(json.error);if(!abort.signal.aborted){setRows(previous=>after?[...previous,...json.plays]:json.plays);setHasMore(json.hasMore);}}catch(e){if(!abort.signal.aborted)setError((e as Error).message);}finally{if(!abort.signal.aborted)setBusy(false);}};
 useEffect(()=>{setRows([]);if(popup||mode==="range"&&start||kind!=="all")void fetchRows();return()=>abortRef.current?.abort();},[popup,mode,kind,start,end]);
 useEffect(()=>{if(!popup)return;const close=(event:KeyboardEvent)=>{if(event.key==="Escape"){setFull(false);if(end&&end!==start){setMode("latest");setStart("");setEnd("");}}};document.addEventListener("keydown",close);return()=>document.removeEventListener("keydown",close);},[popup,end,start]);
 const filters=<><div className="game-history-segments"><button className={mode==="latest"?"selected":""} onClick={()=>{setMode("latest");setStart("");setEnd("");}}>ล่าสุด</button><button className={mode==="range"?"selected":""} onClick={()=>setMode("range")}>▦ เลือกช่วงเวลา</button></div><div className="game-history-filters"><GameSelect aria-label="ประเภทรางวัล" value={kind} onChange={e=>setKind(e.target.value)}><option value="all">ทุกประเภท</option><option value="points">แต้มสมาชิก</option><option value="coupon">คูปอง</option><option value="item">ของรางวัล</option></GameSelect><DateRangePicker start={start} end={end} allowSingleDay label="เลือกวันที่หรือช่วงเวลา" onChange={(a,b)=>{setStart(a);setEnd(b);setMode("range");}}/></div></>;
 const showRows=(items:Row[],grouped=false)=>items.length?<div className="game-history-rows">{items.map((row,index)=>{const month=bangkokDay(row.created_at).slice(0,7),previous=index?bangkokDay(items[index-1].created_at).slice(0,7):"";return <div key={row.id}>{grouped&&month!==previous&&<h3 className="game-history-month">{new Date(`${month}-01T12:00:00Z`).toLocaleDateString("th-TH",{month:"long",year:"numeric",timeZone:"Asia/Bangkok"})}</h3>}<article><ProfilePhoto src={row.member?.line_picture_url} size={40} alt={row.member?.name||"สมาชิก"}/><div><strong>{row.member?.name||"สมาชิก"}</strong><small>{new Date(row.created_at).toLocaleString("th-TH",{timeZone:"Asia/Bangkok",day:"numeric",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"})}</small></div><span className={`game-history-prize kind-${row.prize.kind}`}><Gift size={14}/>{row.prize.title}</span></article></div>;})}</div>:<div className="game-history-empty">ยังไม่มีรายการในช่วงนี้ 🐾</div>;
 const close=()=>{setFull(false);if(end&&end!==start){setMode("latest");setStart("");setEnd("");}};
 return <section className="game-history-card"><header><span><History size={20}/>ประวัติรายการ</span><button onClick={()=>setFull(true)}>ดูทั้งหมด<ArrowUpRight size={15}/></button></header>{canClear&&!preview&&<GameHistoryCleanup onCleared={()=>{setRows([]);setFull(false);setMode("latest");setKind("all");setStart("");setEnd("");onCleared?.();}}/>}{!popup&&filters}{error&&<p role="alert" className="paw-alert">{error}</p>}{!popup&&showRows((mode==="range"&&start||kind!=="all"?rows:local).slice(0,5))}{popup&&<div className="preview-modal game-history-modal" role="dialog" aria-modal="true" aria-labelledby="game-history-modal-title"><button className="preview-backdrop" aria-label="ปิดประวัติ" onClick={close}/><section><button className="preview-close" aria-label="ปิด" onClick={close}><X/></button><h2 id="game-history-modal-title"><History size={22}/>ประวัติการเล่น</h2>{filters}{error&&<p className="paw-alert" role="alert">{error}</p>}{showRows(rows,true)}{hasMore&&<button className="game-history-more" disabled={busy} onClick={()=>void fetchRows(rows[rows.length-1])}>{busy?"กำลังโหลด…":"ดูรายการเพิ่ม"}</button>}</section></div>}</section>;
}
