"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { BookOpen, Gift, History, PawPrint, Play, Ticket, X } from "lucide-react";
import QRCode from "qrcode";
import { GameStage, type StageSpin } from "./game-stage";
import { practicePrizes } from "@/lib/games/preview";
import type { GameGrant, GamePlay, MemberGames, PublicPrize } from "@/lib/games/types";

const empty: MemberGames = { ready: false, program: { purchaseThreshold: 500, earningEnabled: false }, games: [], wallet: { balance: 0, carry: 0 }, plays: [], grants: [] };
const when=(date:string)=>new Date(date).toLocaleString("th-TH",{dateStyle:"medium",timeStyle:"short"});
function prizeText(p:PublicPrize){return p.kind==="points"?`${p.points.toLocaleString()} แต้ม`:p.kind==="coupon"?`ส่วนลด ${p.discountValue}${p.discountType==="percent"?"%":" บาท"}`:"รับของที่ร้าน";}
type Pending={gameKey:string;requestId:string;version:number};
export function MemberGameHub({ member, idToken, accessToken, preview=false, onPointsUpdated }: { member: { memberCode: string; name: string; points: number; linePictureUrl?: string|null }; idToken?: string; accessToken?: string; preview?: boolean; onPointsUpdated?: (points:number)=>void }) {
  const [data,setData]=useState<MemberGames>(empty), [key,setKey]=useState("paw-wheel"), [practice,setPractice]=useState(preview), [busy,setBusy]=useState(false), [error,setError]=useState(""), [spin,setSpin]=useState<StageSpin|null>(null), [slots,setSlots]=useState<PublicPrize[]|null>(null), [dialog,setDialog]=useState<"rules"|"history"|"rewards"|"win"|null>(null), [result,setResult]=useState<GamePlay|null>(null), [qr,setQr]=useState(""), [selected,setSelected]=useState<GameGrant|null>(null);
  const lock=useRef(false), outcome=useRef<GamePlay|null>(null), demo=useRef(false), pending=useRef<Pending|null>(null), mounted=useRef(true), pointsCallback=useRef(onPointsUpdated), dialogRef=useRef<HTMLDialogElement>(null);
  pointsCallback.current=onPointsUpdated;
  const storageKey=`tammy-game-pending:${accessToken?.startsWith("test:")?"test":"live"}:${member.memberCode}`;
  const call=useCallback(async(body:object)=>{const response=await fetch("/api/line/member/games",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...body,idToken,accessToken}),cache:"no-store"});const json=await response.json();if(!response.ok) {const err=new Error(json.error||"เชื่อมต่อไม่สำเร็จ") as Error&{status:number};err.status=response.status;throw err;}return json;},[idToken,accessToken]);
  const refresh=useCallback(async()=>{if(preview)return;const next:MemberGames=await call({action:"status"});if(mounted.current)setData(next);},[call,preview]);
  useEffect(()=>{mounted.current=true;void refresh().catch(e=>{if(mounted.current)setError(e.message);});let stored:Pending|null=null;try{stored=JSON.parse(sessionStorage.getItem(storageKey)||"null");}catch{}if(stored&&!preview){pending.current=stored;lock.current=true;setBusy(true);void call({action:"recover",...stored}).then(json=>{if(!mounted.current)return;if(json.play){outcome.current=json.play;setResult(json.play);setDialog("win");try{sessionStorage.removeItem(storageKey);}catch{}pending.current=null;if(typeof json.play.points_after==="number")pointsCallback.current?.(json.play.points_after);void refresh().catch(()=>{});}else setError("มีรอบที่ยังไม่ยืนยัน กดหมุนอีกครั้งเพื่อตรวจรอบเดิมโดยไม่หักซ้ำ");}).catch(e=>{if(mounted.current)setError(e.message);}).finally(()=>{lock.current=false;if(mounted.current)setBusy(false);});}return()=>{mounted.current=false;};},[call,refresh,preview,storageKey]);
  useEffect(()=>{if(preview)return;const update=()=>{if(!document.hidden)void refresh().catch(()=>{});};window.addEventListener("focus",update);document.addEventListener("visibilitychange",update);const timer=setInterval(update,30000);return()=>{window.removeEventListener("focus",update);document.removeEventListener("visibilitychange",update);clearInterval(timer);};},[preview,refresh]);
  useEffect(()=>{if(!dialog)return;const previous=document.activeElement as HTMLElement|null;const el=dialogRef.current;if(el&&!el.open)el.showModal();return()=>{el?.close();if(previous?.isConnected)previous.focus({preventScroll:true});};},[dialog]);
  useEffect(()=>{if(!selected||dialog!=="rewards")return;let current=true;setQr("");void QRCode.toDataURL(`TAMMY-GAME:${selected.qr_token}`,{width:280,margin:2}).then(v=>{if(current)setQr(v);});const timer=setInterval(()=>void refresh().catch(()=>{}),5000);return()=>{current=false;clearInterval(timer);};},[selected,refresh,dialog]);
  const game=data.games.find(g=>g.key===key)||data.games[0];const playingDemo=practice||preview;const displayed=slots || (playingDemo?practicePrizes:game?.prizes.length?game.prizes:practicePrizes);
  const finish=()=>{const play=outcome.current;if(!play)return;setResult(play);setDialog("win");setBusy(false);lock.current=false;if(!demo.current){if(typeof play.points_after==="number")onPointsUpdated?.(play.points_after);void refresh().catch(e=>setError(e.message));}};
  const start=async()=>{
    if(lock.current)return;lock.current=true;setBusy(true);setError("");demo.current=playingDemo;
    try{
      let play:GamePlay;
      if(playingDemo){const r=new Uint32Array(1);crypto.getRandomValues(r);play={id:crypto.randomUUID(),game_key:"practice",prize:practicePrizes[r[0]%practicePrizes.length],created_at:new Date().toISOString(),tickets_before:0,tickets_after:0,slots:practicePrizes};}
      else {if(!game&&!pending.current)throw new Error("ร้านยังไม่เปิดกิจกรรม ลองโหมดฝึกก่อนได้ครับ");const req=pending.current||{gameKey:game!.key,requestId:crypto.randomUUID(),version:game!.version};pending.current=req;try{sessionStorage.setItem(storageKey,JSON.stringify(req));}catch{}const json=await call({action:"play",...req});play=json.play;pending.current=null;try{sessionStorage.removeItem(storageKey);}catch{} }
      outcome.current=play;setSlots(play.slots||displayed);setSpin({key:play.id,targetId:play.prize.id});
    }catch(e){const err=e as Error&{status?:number};setError(err.message);if(err.status&&err.status<500){pending.current=null;try{sessionStorage.removeItem(storageKey);}catch{}void refresh().catch(()=>{});}setBusy(false);lock.current=false;}
  };
  const currentGrant=selected?data.grants.find(g=>g.id===selected.id)||selected:null;
  const grantUsable=currentGrant?.status==="available"&&(!currentGrant.expires_at||new Date(currentGrant.expires_at).getTime()>Date.now());
  return <section className="paw-game paw-game--cinematic" aria-label="วงล้ออุ้งเท้า">
    <div className="paw-hud"><span className="paw-profile">{member.linePictureUrl?<img src={member.linePictureUrl} alt=""/>:<PawPrint size={23}/>}<b>{member.name}</b></span><span>🪙 <b>{member.points.toLocaleString()}</b><small>แต้ม</small></span><span><Ticket size={20}/><b>{Math.max(0,data.wallet.balance)+(data.wallet.testBalance||0)}</b><small>{data.wallet.testBalance?`สิทธิ์ · ทดสอบ ${data.wallet.testBalance}`:"สิทธิ์"}</small></span></div>
    <header className="paw-title"><h2><PawPrint aria-hidden="true"/>{game?.name||"วงล้ออุ้งเท้า"}<PawPrint aria-hidden="true"/></h2></header>
    {data.games.length>1&&<div className="paw-game-picker">{data.games.map(g=><button key={g.key} disabled={busy} className={game?.key===g.key?"selected":""} onClick={()=>{setKey(g.key);setSlots(null);setSpin(null);}}>{g.name}</button>)}</div>}
    <div className="paw-purchase"><div><span>ซื้อสะสมครบ <b>฿{data.program.purchaseThreshold.toLocaleString()}</b> รับ 1 สิทธิ์</span><b>อีก ฿{Math.max(0,data.program.purchaseThreshold-data.wallet.carry).toLocaleString()}</b></div><progress value={Math.min(data.wallet.carry,data.program.purchaseThreshold)} max={data.program.purchaseThreshold}/><small>{data.program.earningEnabled?"สะสมจากยอดซื้อใหม่ · สิทธิ์เก็บไว้เล่นครั้งต่อไปได้":"ร้านยังไม่เปิดสะสมสิทธิ์จากยอดซื้อ"}{data.wallet.balance<0&&" · สิทธิ์จากรายการที่ยกเลิกจะชดเชยด้วยยอดซื้อครั้งถัดไป"}</small></div>
    <GameStage engine={game?.engine||"wheel"} prizes={displayed} spin={spin} onFinish={finish} cinematic/>
    <div className="paw-controls"><button className="paw-spin" disabled={busy||!playingDemo&&!pending.current&&(!game||Math.max(0,data.wallet.balance)+(data.wallet.testBalance||0)<1)} onClick={()=>void start()}><PawPrint/>{busy?"วงล้อกำลังหมุน…":pending.current?"ตรวจรอบเดิม":playingDemo?"หมุนทดลองเล่น":"หมุนรับรางวัล"}<Play size={19}/></button><p>{playingDemo?"โหมดฝึก · ไม่ใช้สิทธิ์และไม่ได้รับรางวัลจริง":"ใช้ 1 สิทธิ์ต่อรอบ · ผลบันทึกอัตโนมัติ"}</p>{!preview&&<button className="paw-practice" disabled={busy||Boolean(pending.current)} onClick={()=>{setPractice(v=>!v);setSlots(null);setSpin(null);}}>{practice?"กลับไปเล่นรับรางวัล":"ลองฝึกเล่นฟรี"}</button>}</div>
    {error&&<p className="paw-alert" role="status">{error}<button onClick={()=>void refresh().then(()=>setError("")).catch(e=>setError(e.message))}>ตรวจอีกครั้ง</button></p>}
    <nav className="paw-actions"><button onClick={()=>setDialog("rules")}><BookOpen/>กติกา</button><button onClick={()=>setDialog("history")}><History/>ประวัติ</button><button onClick={()=>{setSelected(null);setDialog("rewards");}}><Gift/>รางวัลของฉัน</button></nav>
    {dialog&&createPortal(<dialog ref={dialogRef} className="paw-dialog" aria-label={dialog==="rules"?"กติกาวงล้ออุ้งเท้า":dialog==="history"?"ประวัติการเล่น":dialog==="rewards"?"รางวัลของฉัน":"ผลการหมุนรางวัล"} onCancel={()=>setDialog(null)} onClick={e=>{if(e.target===e.currentTarget)setDialog(null);}}><div className="paw-dialog-inner"><button className="paw-close" aria-label="ปิด" onClick={()=>setDialog(null)}><X/></button>
      {dialog==="win"&&result&&<><div className="paw-win-icon">{result.prize.image?<img src={result.prize.image} alt=""/>:result.prize.kind==="points"?"🪙":result.prize.kind==="coupon"?"🎟️":"🎁"}</div><small>{demo.current?"ผลทดลองเล่น":"ยินดีด้วย!"}</small><h2>{result.prize.title}</h2><p>{prizeText(result.prize)}</p><p>{demo.current?"รอบนี้เป็นการฝึก ไม่เพิ่มแต้มและไม่แจกของรางวัลจริง":result.prize.kind==="points"?"เพิ่มแต้มเข้าบัญชีเรียบร้อยแล้ว":"เก็บรางวัลไว้แล้ว เปิด QR ในรางวัลของฉันเพื่อรับที่ร้าน"}</p><button className="paw-primary" onClick={()=>{setDialog(result.prize.kind!=="points"&&!demo.current?"rewards":null);setSelected(null);}}> {result.prize.kind!=="points"&&!demo.current?"เปิดรางวัลของฉัน":"เล่นต่อ"}</button></>}
      {dialog==="rules"&&<><small>HOW TO PLAY</small><h2>กติกาวงล้ออุ้งเท้า</h2><ol><li>ยอดซื้อใหม่สะสมครบ {data.program.purchaseThreshold.toLocaleString()} บาท รับ 1 สิทธิ์ ยอดที่เหลือยกไปครั้งถัดไป</li><li>ใช้ 1 สิทธิ์ต่อรอบ เก็บสิทธิ์ไว้เล่นภายหลังได้ ไม่มีสิทธิ์ฟรีรายวัน</li><li>แต้มเข้าบัญชีอัตโนมัติ คูปองและสินค้าเก็บใน “รางวัลของฉัน”</li><li>คูปองมีเงื่อนไขและวันหมดอายุตามที่แสดงบนรางวัล ต้องแสดง QR ให้พนักงาน</li><li>โหมดฝึกไม่มีรางวัลจริง หากเน็ตหลุด ระบบตรวจรอบเดิมให้ ไม่หักสิทธิ์ซ้ำ</li><li>ยกเลิกยอดซื้อแล้วสิทธิ์จากยอดนั้นจะถูกปรับคืน หากใช้ไปแล้ว ยอดซื้อถัดไปจะชดเชยก่อน</li></ol><p>ขนาดช่องบนวงล้อเป็นภาพประกอบ การได้รับรางวัลขึ้นอยู่กับเงื่อนไขกิจกรรมและจำนวนรางวัลคงเหลือ</p></>}
      {dialog==="history"&&<><small>PLAY HISTORY</small><h2>ประวัติการเล่น</h2><p>100 รายการล่าสุด</p>{!data.plays.length?<p className="paw-empty">เริ่มหมุนครั้งแรกแล้วประวัติจะอยู่ตรงนี้ 🐾</p>:data.plays.map(p=><div className="paw-history" key={p.id}><span>{p.prize.kind==="points"?"🪙":"🎁"}</span><div><b>{p.prize.title}</b><small>{when(p.created_at)}</small></div><b>−1 สิทธิ์</b></div>)}</>}
      {dialog==="rewards"&&<><small>MY PRIZES</small><h2>รางวัลของฉัน</h2>{selected&&currentGrant?<><h3>{currentGrant.title}</h3><p>{prizeText(currentGrant.snapshot)}</p>{currentGrant.kind==="coupon"&&<p>ยอดซื้อขั้นต่ำ ฿{currentGrant.snapshot.minSpend.toLocaleString()}{currentGrant.snapshot.maxDiscount!==null&&` · ลดสูงสุด ฿${currentGrant.snapshot.maxDiscount}`}</p>}<p>{currentGrant.expires_at?`ใช้ก่อน ${when(currentGrant.expires_at)}`:"ไม่กำหนดวันหมดอายุ"}</p>{grantUsable&&qr?<img className="paw-qr" src={qr} alt="QR รับรางวัล แสดงให้พนักงานร้าน"/>:<p>{currentGrant.status==="used"?"ใช้รางวัลแล้ว":grantUsable?"กำลังสร้าง QR…":"รางวัลหมดอายุแล้ว"}</p>}<button className="paw-primary" onClick={()=>setSelected(null)}>กลับไปดูรางวัล</button></>:!data.grants.length?<p className="paw-empty">คูปองและของขวัญที่ได้รับจะอยู่ตรงนี้ 🎁</p>:data.grants.map(g=><button className="paw-grant" key={g.id} onClick={()=>setSelected(g)}><span>🎁</span><div><b>{g.title}</b><small>{g.status==="used"?"ใช้แล้ว":g.expires_at&&new Date(g.expires_at).getTime()<=Date.now()?"หมดอายุ":g.expires_at?`ใช้ก่อน ${when(g.expires_at)}`:"พร้อมใช้"}</small></div><span>ดู QR ›</span></button>)}</>}
    </div></dialog>,document.body)}
  </section>;
}
